CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR2(100) NOT NULL,
    customer_email VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE menu_items (
    item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR2(100) NOT NULL UNIQUE,
    item_price NUMBER(6,2) NOT NULL CHECK (item_price > 0)
);

CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    order_date DATE DEFAULT SYSDATE NOT NULL,
    order_total_amount NUMBER(8,2) NOT NULL CHECK (order_total_amount >= 0),
    CONSTRAINT fk_customer FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    item_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    line_total NUMBER(8,2) NOT NULL CHECK (line_total >= 0),
    CONSTRAINT fk_order FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_item FOREIGN KEY (item_id)
        REFERENCES menu_items(item_id)
);

CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_time TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    event_type VARCHAR2(100) NOT NULL,
    object_type VARCHAR2(100),
    object_id NUMBER,
    operation VARCHAR2(100),
    details VARCHAR2(4000),
    error_code NUMBER,
    error_message VARCHAR2(2000),
    source_proc VARCHAR2(100)
);

CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_item_id ON order_items (item_id);
